package org.jhipster.projectintern.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HotelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAllPropertiesEquals(Hotel expected, Hotel actual) {
        assertHotelAutoGeneratedPropertiesEquals(expected, actual);
        assertHotelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAllUpdatablePropertiesEquals(Hotel expected, Hotel actual) {
        assertHotelUpdatableFieldsEquals(expected, actual);
        assertHotelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelAutoGeneratedPropertiesEquals(Hotel expected, Hotel actual) {
        assertThat(expected)
            .as("Verify Hotel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelUpdatableFieldsEquals(Hotel expected, Hotel actual) {
        assertThat(expected)
            .as("Verify Hotel relevant properties")
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getNumeroTelephone()).as("check numeroTelephone").isEqualTo(actual.getNumeroTelephone()))
            .satisfies(e -> assertThat(e.getPays()).as("check pays").isEqualTo(actual.getPays()))
            .satisfies(e -> assertThat(e.getVille()).as("check ville").isEqualTo(actual.getVille()))
            .satisfies(e -> assertThat(e.getVueS()).as("check vueS").isEqualTo(actual.getVueS()))
            .satisfies(e -> assertThat(e.getCapacite()).as("check capacite").isEqualTo(actual.getCapacite()))
            .satisfies(e -> assertThat(e.getNotation()).as("check notation").isEqualTo(actual.getNotation()))
            .satisfies(e -> assertThat(e.getLienUnique()).as("check lienUnique").isEqualTo(actual.getLienUnique()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHotelUpdatableRelationshipsEquals(Hotel expected, Hotel actual) {
        assertThat(expected)
            .as("Verify Hotel relationships")
            .satisfies(e -> assertThat(e.getUiConfigurations()).as("check uiConfigurations").isEqualTo(actual.getUiConfigurations()))
            .satisfies(e -> assertThat(e.getEmailConfig()).as("check emailConfig").isEqualTo(actual.getEmailConfig()))
            .satisfies(e -> assertThat(e.getAuthConfig()).as("check authConfig").isEqualTo(actual.getAuthConfig()))
            .satisfies(
                e -> assertThat(e.getHotelAdministrateur()).as("check hotelAdministrateur").isEqualTo(actual.getHotelAdministrateur())
            );
    }
}
